name: 🏷️ Gemini CLI - Clasificación de Issues

# =============================================================
# WORKFLOW: Gemini CLI - Clasificación de Issues
# =============================================================
# Este workflow utiliza Gemini CLI para analizar y clasificar issues automáticamente.
#
# ¿Qué hace?
# - Detecta nuevos issues, comentarios con comandos especiales o ejecuciones manuales.
# - Analiza el contenido del issue y sugiere etiquetas, prioridad, complejidad y área.
# - Comenta el análisis y aplica etiquetas automáticamente.
#
# Disparadores principales:
# - Cuando se crea, edita o reabre un issue.
# - Cuando se comenta en un issue usando @gemini-cli y el comando /triage.
# - Cuando se ejecuta manualmente desde la interfaz de GitHub (workflow_dispatch).
# =============================================================

on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Número del issue o PR a clasificar"
        required: false
        type: string

jobs:
  triage:
    name: Clasificar Issue con Gemini
    runs-on: ubuntu-latest

    # ----------------------------------------------------------------------
    # CONDICIÓN DE EJECUCIÓN (if):
    # Solo ejecuta el job si se cumple al menos uno de estos casos:
    # 1. El workflow fue lanzado manualmente (workflow_dispatch)
    # 2. Se abrió un nuevo issue (event_name == 'issues' && action == 'opened')
    # 3. Se comentó en un issue, el comentario menciona a @gemini-cli y contiene /triage
    #    (event_name == 'issue_comment' && ...)
    # 4. Se comentó en un PR, el comentario menciona a @gemini-cli y contiene /triage
    #    (event_name == 'pull_request_review_comment' && ...)
    # Esto evita ejecuciones innecesarias y asegura que solo actúe en los casos relevantes.
    # ----------------------------------------------------------------------
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && github.event.action == 'opened') ||
      (github.event_name == 'issue_comment' && 
       github.event.issue != null &&
       contains(github.event.comment.body, '@gemini-cli') && 
       contains(github.event.comment.body, '/triage')) ||
      (github.event_name == 'pull_request_review_comment' && 
       contains(github.event.comment.body, '@gemini-cli') && 
       contains(github.event.comment.body, '/triage'))

    permissions:
      contents: read
      issues: write
      pull-requests: write

  # ----------------------------------------------------------------------
  # PERMISOS:
  # - contents:read        → Permite leer archivos del repositorio si Gemini lo requiere para contexto.
  # - issues:write         → Necesario para publicar comentarios y aplicar etiquetas al issue.
  # - pull-requests:write  → Necesario para comentar en PRs cuando se use /triage en PRs.
  # ----------------------------------------------------------------------

    steps:
      - name: Obtener información del issue
        # -------------------------------------------------------------
        # Paso 1: Recopilar número, título, cuerpo y URL del issue.
        # - Si el evento es 'issues', toma los datos directamente.
        # - Si es 'issue_comment' o 'workflow_dispatch', consulta el issue por API.
        # Esto permite que el workflow funcione tanto en triggers automáticos como manuales.
        # -------------------------------------------------------------
        id: get-issue
        uses: actions/github-script@v7
        with:
          script: |
            let issueNumber;
            let issueData;
            
            if (context.eventName === 'issues') {
              // Issue creado directamente
              issueNumber = context.issue.number;
              issueData = context.payload.issue;
            } else if (context.eventName === 'issue_comment') {
              // Comentario en issue
              issueNumber = context.issue.number;
              const { data: issue } = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              issueData = issue;
            } else if (context.eventName === 'workflow_dispatch') {
              // Ejecución manual
              issueNumber = context.payload.inputs.issue_number || context.issue.number;
              const { data: issue } = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              issueData = issue;
            }
            
            core.setOutput('issue_number', issueNumber);
            core.setOutput('issue_title', issueData.title);
            core.setOutput('issue_body', issueData.body);
            core.setOutput('issue_url', issueData.html_url);

      - name: Ejecutar Gemini CLI para Clasificación
        # -------------------------------------------------------------
        # Paso 2: Enviar prompt a Gemini CLI con el título y cuerpo del issue.
        # El prompt explica a Gemini cómo debe analizar y clasificar el issue.
        # Gemini responde con un análisis estructurado y sugerencias.
        # -------------------------------------------------------------
        id: gemini-analysis
        uses: google-github-actions/run-gemini-cli@v0.1.10
        with:
          prompt: |
            Eres un experto en gestión de proyectos y clasificación de issues de software.

            **ISSUE A ANALIZAR:**
            Título: ${{ steps.get-issue.outputs.issue_title }}
            Descripción: ${{ steps.get-issue.outputs.issue_body }}

            Tu tarea es analizar el siguiente issue y:

            1. **Categorizar** el tipo de issue:
               - `bug` - Errores o fallos
               - `feature` - Nuevas funcionalidades
               - `enhancement` - Mejoras a funcionalidad existente
               - `documentation` - Relacionado con documentación
               - `question` - Preguntas o consultas
               - `maintenance` - Tareas de mantenimiento
               - `security` - Problemas de seguridad

            2. **Determinar prioridad**:
               - `priority-critical` - Crítico, bloquea funcionalidad principal
               - `priority-high` - Alto, impacta usuarios importantes
               - `priority-medium` - Medio, mejora experiencia
               - `priority-low` - Bajo, mejora menor

            3. **Evaluar complejidad**:
               - `complexity-simple` - Solución directa, pocas horas
               - `complexity-medium` - Requiere análisis, días
               - `complexity-complex` - Cambios arquitectónicos, semanas

            4. **Identificar área**:
               - `area-frontend` - Interfaz de usuario
               - `area-backend` - Lógica del servidor
               - `area-database` - Base de datos
               - `area-api` - APIs y servicios
               - `area-devops` - Infraestructura y despliegue
               - `area-testing` - Pruebas y QA

            **Formato de respuesta**:

            ## 🏷️ Clasificación Automática

            **Tipo**: [tipo]
            **Prioridad**: [prioridad]  
            **Complejidad**: [complejidad]
            **Área**: [área]

            ## 📋 Análisis

            [Breve explicación del issue y razón de la clasificación]

            ## 🎯 Recomendaciones

            - [Sugerencia 1]
            - [Sugerencia 2]

            Responde siempre en español y sé específico en tu análisis.

          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}

      - name: Comentar clasificación en el issue
        # -------------------------------------------------------------
        # Paso 3: Si Gemini responde correctamente, comentar el análisis en el issue
        # y aplicar etiquetas automáticamente.
        # - Extrae patrones de la respuesta para convertirlos en labels.
        # - Aplica todas las etiquetas encontradas (tipo, prioridad, complejidad, área).
        # -------------------------------------------------------------
        if: success()
        uses: actions/github-script@v7
        env:
          GEMINI_RESPONSE: ${{ steps.gemini-analysis.outputs.summary }}
        with:
          script: |
            const issueNumber = ${{ steps.get-issue.outputs.issue_number }};

            if (issueNumber) {
              const geminiResponse = process.env.GEMINI_RESPONSE || 'No se pudo obtener la respuesta de Gemini.';
              
              // Comentar la clasificación
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `🤖 **Clasificación Automática por Gemini CLI**\n\n${geminiResponse}`
              });
              
              // Extraer y aplicar labels automáticamente
              const labels = [];
              
              // Buscar patrones de labels en la respuesta
              const typeMatch = geminiResponse.match(/\*\*Tipo\*\*:\s*`?([^`\n]*)`?/);
              const priorityMatch = geminiResponse.match(/\*\*Prioridad\*\*:\s*`?([^`\n]*)`?/);
              const complexityMatch = geminiResponse.match(/\*\*Complejidad\*\*:\s*`?([^`\n]*)`?/);
              const areaMatch = geminiResponse.match(/\*\*Área\*\*:\s*`?([^`\n]*)`?/);
              
              if (typeMatch) labels.push(typeMatch[1].trim());
              if (priorityMatch) labels.push(priorityMatch[1].trim());
              if (complexityMatch) labels.push(complexityMatch[1].trim());
              if (areaMatch) {
                // Manejar múltiples áreas separadas por comas
                const areas = areaMatch[1].split(',').map(area => area.trim().replace(/`/g, ''));
                labels.push(...areas);
              }
              
              // Aplicar labels al issue
              if (labels.length > 0) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  labels: labels
                });
                
                console.log(`Labels aplicados: ${labels.join(', ')}`);
              }
            }

      - name: Comentar si hay error
        # -------------------------------------------------------------
        # Paso 4: Si ocurre un error en cualquier paso anterior, publica un comentario
        # en el issue con un mensaje de error y un enlace a los logs de la ejecución.
        # -------------------------------------------------------------
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = ${{ steps.get-issue.outputs.issue_number }};
                              
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: '❌ Error al clasificar el issue. [Ver logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
              });
            }
