name: 🏷️ Gemini CLI - Clasificación de Issues

on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Número del issue a clasificar"
        required: false
        type: string

jobs:
  triage:
    name: Clasificar Issue con Gemini
    runs-on: ubuntu-latest

    # Ejecutar solo: 1) automáticamente en nuevos issues, 2) manualmente con /triage
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && github.event.action == 'opened') ||
      (github.event_name == 'issue_comment' && 
       github.event.issue != null &&
       contains(github.event.comment.body, '@gemini-cli') && 
       contains(github.event.comment.body, '/triage'))

    permissions:
      contents: read
      issues: write

    steps:
      - name: Obtener información del issue
        id: get-issue
        uses: actions/github-script@v7
        with:
          script: |
            let issueNumber;
            let issueData;
            
            if (context.eventName === 'issues') {
              // Issue creado directamente
              issueNumber = context.issue.number;
              issueData = context.payload.issue;
            } else if (context.eventName === 'issue_comment') {
              // Comentario en issue
              issueNumber = context.issue.number;
              const { data: issue } = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              issueData = issue;
            } else if (context.eventName === 'workflow_dispatch') {
              // Ejecución manual
              issueNumber = context.payload.inputs.issue_number || context.issue.number;
              const { data: issue } = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              issueData = issue;
            }
            
            core.setOutput('issue_number', issueNumber);
            core.setOutput('issue_title', issueData.title);
            core.setOutput('issue_body', issueData.body);
            core.setOutput('issue_url', issueData.html_url);

      - name: Ejecutar Gemini CLI para Clasificación
        id: gemini-analysis
        uses: google-github-actions/run-gemini-cli@v0.1.10
        with:
          prompt: |
            Eres un experto en gestión de proyectos y clasificación de issues de software.

            **ISSUE A ANALIZAR:**
            Título: ${{ steps.get-issue.outputs.issue_title }}
            Descripción: ${{ steps.get-issue.outputs.issue_body }}

            Tu tarea es analizar el siguiente issue y:

            1. **Categorizar** el tipo de issue:
               - `bug` - Errores o fallos
               - `feature` - Nuevas funcionalidades
               - `enhancement` - Mejoras a funcionalidad existente
               - `documentation` - Relacionado con documentación
               - `question` - Preguntas o consultas
               - `maintenance` - Tareas de mantenimiento
               - `security` - Problemas de seguridad

            2. **Determinar prioridad**:
               - `priority-critical` - Crítico, bloquea funcionalidad principal
               - `priority-high` - Alto, impacta usuarios importantes
               - `priority-medium` - Medio, mejora experiencia
               - `priority-low` - Bajo, mejora menor

            3. **Evaluar complejidad**:
               - `complexity-simple` - Solución directa, pocas horas
               - `complexity-medium` - Requiere análisis, días
               - `complexity-complex` - Cambios arquitectónicos, semanas

            4. **Identificar área**:
               - `area-frontend` - Interfaz de usuario
               - `area-backend` - Lógica del servidor
               - `area-database` - Base de datos
               - `area-api` - APIs y servicios
               - `area-devops` - Infraestructura y despliegue
               - `area-testing` - Pruebas y QA

            **Formato de respuesta**:

            ## 🏷️ Clasificación Automática

            **Tipo**: [tipo]
            **Prioridad**: [prioridad]  
            **Complejidad**: [complejidad]
            **Área**: [área]

            ## 📋 Análisis

            [Breve explicación del issue y razón de la clasificación]

            ## 🎯 Recomendaciones

            - [Sugerencia 1]
            - [Sugerencia 2]

            Responde siempre en español y sé específico en tu análisis.

          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}

      - name: Comentar clasificación en el issue
        if: success()
        uses: actions/github-script@v7
        env:
          GEMINI_RESPONSE: ${{ steps.gemini-analysis.outputs.summary }}
        with:
          script: |
            const issueNumber = ${{ steps.get-issue.outputs.issue_number }};

            if (issueNumber) {
              const geminiResponse = process.env.GEMINI_RESPONSE || 'No se pudo obtener la respuesta de Gemini.';
              
              // Comentar la clasificación
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `🤖 **Clasificación Automática por Gemini CLI**\n\n${geminiResponse}`
              });
              
              // Extraer y aplicar labels automáticamente
              const labels = [];
              
              // Buscar patrones de labels en la respuesta
              const typeMatch = geminiResponse.match(/\*\*Tipo\*\*:\s*`?([^`\n]*)`?/);
              const priorityMatch = geminiResponse.match(/\*\*Prioridad\*\*:\s*`?([^`\n]*)`?/);
              const complexityMatch = geminiResponse.match(/\*\*Complejidad\*\*:\s*`?([^`\n]*)`?/);
              const areaMatch = geminiResponse.match(/\*\*Área\*\*:\s*`?([^`\n]*)`?/);
              
              if (typeMatch) labels.push(typeMatch[1].trim());
              if (priorityMatch) labels.push(priorityMatch[1].trim());
              if (complexityMatch) labels.push(complexityMatch[1].trim());
              if (areaMatch) {
                // Manejar múltiples áreas separadas por comas
                const areas = areaMatch[1].split(',').map(area => area.trim().replace(/`/g, ''));
                labels.push(...areas);
              }
              
              // Aplicar labels al issue
              if (labels.length > 0) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issueNumber,
                  labels: labels
                });
                
                console.log(`Labels aplicados: ${labels.join(', ')}`);
              }
            }

      - name: Comentar si hay error
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = ${{ steps.get-issue.outputs.issue_number }};
                              
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: '❌ Error al clasificar el issue. [Ver logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
              });
            }
